spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true  # ✅ SQL 실행 로그 보기

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always  # ✅ data.sql 실행
